=== HauptmannEck/oss-dataturbine/trunk/dev/rtdsm/geonRBNB/srcConfig.dtd
<!ELEMENT SourceConfig (source*) >

<!ELEMENT source (mainChannels,feedback)>
<!ATTLIST source name CDATA #REQUIRED>

<!ELEMENT mainChannels (orbParams)>

<!ELEMENT feedback (orbParams)>

<!ELEMENT storage EMPTY>
<!ATTLIST storage cacheSize CDATA #REQUIRED
                    archiveMode CDATA #REQUIRED
                    archiveSize CDATA #REQUIRED>

<!ELEMENT server (channel*)>
<!ATTLIST server uri CDATA #REQUIRED
                 username CDATA #REQUIRED
                 passowrd CDATA #REQUIRED>

<!ELEMENT channel EMPTY>
<!ATTLIST channel name CDATA #REQUIRED
                  dataType CDATA #REQUIRED>

=== HauptmannEck/oss-dataturbine/dev/rtdsm/code/srcConfigFb.xml
<?xml version='1.0'?>
<!DOCTYPE source SYSTEM "srcConfig.dtd">

<SourceConfig>
<source name="12GREENSPN000007014000007E1A285">
  <mainChannels>
    <orbParams orbType="DataTurbine">
      <storage cacheSize="1000" archiveMode="create" archiveSize="10"/>
        <!-- TODO: Support multiple Server mirroring options 
              Multiple uris-->
      <server uri="localhost:3333" username="me" password="mine">
        <channel name="DO_ppm" dataType="double"/>
        <channel name="DO_sat" dataType="double"/>
        <channel name="T" dataType="double"/>
        <channel name="BV" dataType="double"/>
      </server>
    </orbParams>
  </mainChannels>

  <feedback>
    <feedbackOrbParams orbType="DataTurbine">
      <server uri="localhost:3333" username="me" password="mine">
        <channel name="FeedbackCh_1" dataType="double" reqMode="monitor" timeout="-1"/>
      </server>
    </feedbackOrbParams>
  </feedback>
</source>
</SourceConfig>

=== HauptmannEck/oss-dataturbine/trunk/dev/rtdsm/code/srcConfig1.xml
<?xml version='1.0'?>
<!DOCTYPE source SYSTEM "srcConfig.dtd">

<SourceConfig>
<source name="ThinkSource1">
  <mainChannels>
    <orbParams orbType="DataTurbine">
      <storage cacheSize="1000" archiveMode="create" archiveSize="10"/>
        <!-- TODO: Support multiple Server mirroring options 
              Multiple uris-->
      <server uri="localhost:3333" username="me" password="mine">
        <channel name="Temperature" dataType="double"/>
        <channel name="Light" dataType="double"/>
        <channel name="Humidity" dataType="double"/>
      </server>
    </orbParams>
  </mainChannels>
</source>
</SourceConfig>
